//
//  DoneView.swift
//  ProjectName
//
//  Created by AuthorName on 27/09/2014.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

import UIKit

class DoneView: UIView
{
    override func drawRect(rect: CGRect)
    {
        //// Color Declarations
        let color0 = UIColor(red: 0.065, green: 0.372, blue: 0.037, alpha: 1.000)

        //// Page-1
        //// Icons
        //// Imported-Layers Drawing
        var importedLayersPath = UIBezierPath()
        importedLayersPath.moveToPoint(CGPointMake(19.83, 26.35))
        importedLayersPath.addCurveToPoint(CGPointMake(17.62, 26.35), controlPoint1: CGPointMake(19.22, 26.94), controlPoint2: CGPointMake(18.23, 26.94))
        importedLayersPath.addLineToPoint(CGPointMake(13.49, 22.33))
        importedLayersPath.addCurveToPoint(CGPointMake(13.49, 19.59), controlPoint1: CGPointMake(12.71, 21.57), controlPoint2: CGPointMake(12.71, 20.35))
        importedLayersPath.addLineToPoint(CGPointMake(13.52, 19.56))
        importedLayersPath.addCurveToPoint(CGPointMake(16.33, 19.57), controlPoint1: CGPointMake(14.29, 18.81), controlPoint2: CGPointMake(15.55, 18.81))
        importedLayersPath.addLineToPoint(CGPointMake(18.73, 21.9))
        importedLayersPath.addLineToPoint(CGPointMake(25.35, 15.46))
        importedLayersPath.addCurveToPoint(CGPointMake(28.17, 15.46), controlPoint1: CGPointMake(26.13, 14.7), controlPoint2: CGPointMake(27.39, 14.7))
        importedLayersPath.addLineToPoint(CGPointMake(28.2, 15.48))
        importedLayersPath.addCurveToPoint(CGPointMake(28.2, 18.22), controlPoint1: CGPointMake(28.97, 16.24), controlPoint2: CGPointMake(28.97, 17.46))
        importedLayersPath.addLineToPoint(CGPointMake(19.83, 26.35))
        importedLayersPath.addLineToPoint(CGPointMake(19.83, 26.35))
        importedLayersPath.closePath()
        importedLayersPath.moveToPoint(CGPointMake(20.84, 1))
        importedLayersPath.addCurveToPoint(CGPointMake(1, 20.84), controlPoint1: CGPointMake(9.88, 1), controlPoint2: CGPointMake(1, 9.88))
        importedLayersPath.addCurveToPoint(CGPointMake(20.84, 40.68), controlPoint1: CGPointMake(1, 31.8), controlPoint2: CGPointMake(9.88, 40.68))
        importedLayersPath.addCurveToPoint(CGPointMake(40.68, 20.84), controlPoint1: CGPointMake(31.8, 40.68), controlPoint2: CGPointMake(40.68, 31.8))
        importedLayersPath.addCurveToPoint(CGPointMake(20.84, 1), controlPoint1: CGPointMake(40.68, 9.88), controlPoint2: CGPointMake(31.8, 1))
        importedLayersPath.addLineToPoint(CGPointMake(20.84, 1))
        importedLayersPath.closePath()
        importedLayersPath.miterLimit = 4;
        
        importedLayersPath.usesEvenOddFillRule = true;
        
        UIColor.greenColor().setFill()
        importedLayersPath.fill()
        color0.setStroke()
        importedLayersPath.lineWidth = 1
        importedLayersPath.stroke()
    }
}
